/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import controllers.InstructorController;
import controllers.StudentController;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import models.Instructor;
import models.Student;
import models.User;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form MainInterface
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        UserTypeCbx = new javax.swing.JComboBox<>();
        dataCbx = new javax.swing.JComboBox();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Login as");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Don't have an account?");

        Login.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Signup");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        UserTypeCbx.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        UserTypeCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Student", "Instructor" }));
        UserTypeCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTypeCbxActionPerformed(evt);
            }
        });

        dataCbx.setModel(new javax.swing.DefaultComboBoxModel<>());
        dataCbx.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dataCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataCbxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3)
                            .addComponent(Login)
                            .addComponent(jButton2)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dataCbx, 0, 110, Short.MAX_VALUE)
                            .addComponent(UserTypeCbx, 0, 0, Short.MAX_VALUE))))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addComponent(UserTypeCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dataCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        String userType = (String) UserTypeCbx.getSelectedItem();

        if (userType == null || userType.equals("Select...")) {
            JOptionPane.showMessageDialog(null, "Please Select User Type", "No Type Selected", 2);
        } else if (userType.equals("Student")) {
            Student student = (Student) dataCbx.getSelectedItem();
            if (student.getOnlineStatus()) {
                JOptionPane.showMessageDialog(null, "User Already Logged in!", "Dublicate Login error!", 2);
            } else {
                Student_Main IM = new Student_Main(student);
                IM.setVisible(true);
                student.setOnlineStatus(true);
                StudentController.updateStudent(student);
            }

        } else if (userType.equals("Instructor")) {
            Instructor instructor = (Instructor) dataCbx.getSelectedItem();
            if (instructor.getOnlineStatus()) {
                JOptionPane.showMessageDialog(null, "User Already Logged in!", "Dublicate Login error!", 2);
            } else {
                Instructor_Main IM = new Instructor_Main(instructor);
                IM.setVisible(true);
                instructor.setOnlineStatus(true);
                InstructorController.updateInstructor(instructor);
            }
        }

    }//GEN-LAST:event_LoginActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Signup signup = new Signup();
        signup.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void UserTypeCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTypeCbxActionPerformed
        // TODO add your handling code here:
        String selectedInput = (String) UserTypeCbx.getSelectedItem();

        switch (selectedInput) {
            case "Select...":
                DefaultComboBoxModel<String> nullModel = new DefaultComboBoxModel<>();
                dataCbx.setModel(nullModel);
                break;
            case "Student":
                List<Student> students = StudentController.getStudents();
                DefaultComboBoxModel<Student> studentModel = new DefaultComboBoxModel<>();
                for (Student student : students) {
                    studentModel.addElement(student);
                }
                dataCbx.setModel(studentModel);
                break;
            case "Instructor":
                List<Instructor> instructors = InstructorController.getInstructors();
                DefaultComboBoxModel<Instructor> instructorModel = new DefaultComboBoxModel<>();
                for (Instructor instructor : instructors) {
                    instructorModel.addElement(instructor);
                }
                // Set the model to jComboBox2
                dataCbx.setModel(instructorModel);
                break;
        }

    }//GEN-LAST:event_UserTypeCbxActionPerformed

    private void dataCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataCbxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_dataCbxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JComboBox<String> UserTypeCbx;
    private javax.swing.JComboBox dataCbx;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
