/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import controllers.EnrollController;
import controllers.PayPalController;
import controllers.PaymentController;
import controllers.PaymentMethodFactory;
import controllers.StudentController;
import controllers.VisaCardController;
import enums.enrollStatus;
import enums.paymentMethod;
import helpers.SyllabusDisplay;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.ListModel;
import models.Enroll;
import models.Payment;
import models.Paypal;
import models.Student;
import models.Subject;
import models.VisaCard;

/**
 *
 * @author User
 */
public class Student_Main extends javax.swing.JFrame {

    public Student loggedStudent;

    /**
     * Creates new form Student_Main
     */
    public Student_Main() {
        initComponents();
        customInit();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public Student_Main(Student student) {
        this();
        this.loggedStudent = student;
        this.dynamicUsername.setText(student.getUsername());
        List<Enroll> enrollements = EnrollController.getEnrollmentsByStudent(loggedStudent.getId());
        DefaultListModel<Subject> enrolledSubjectsModel = new DefaultListModel<>();
        for (Enroll enroll : enrollements) {
            enrolledSubjectsModel.addElement(enroll.getSubject());
        }
        enrolledSubjectList.setModel(enrolledSubjectsModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void customInit() {
        enrolledSubjectList.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) { // Detects double-click
                    int index = enrolledSubjectList.locationToIndex(evt.getPoint());
                    if (index != -1) {
                        // Ensure model contains Subject objects
                        ListModel<Subject> model = enrolledSubjectList.getModel();
                        if (model.getElementAt(index) instanceof Subject) {
                            Subject selectedSubject = model.getElementAt(index);

                            // Open the syllabus display window
                            SyllabusDisplay syllabusDisplay = new SyllabusDisplay(selectedSubject);
                            syllabusDisplay.setVisible(true);
                        } else {
                            System.err.println("Invalid data type in JList model.");
                        }
                    }
                }
            }
        });

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        enrolledSubjectList = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        selectSubjectCbx = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prerequisiteList = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        selectedSubjectPriceLbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        completedEnrollementList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        pendingPaymentList = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        selectedPaymentMethod = new javax.swing.JComboBox<>();
        dynamicPaymentMethodPanel = new javax.swing.JPanel();
        dynamicUsername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Student");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Welcome!");

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Enrolled Subjects");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Recurring Tests");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Recurring Meetings");

        jList3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(jList3);

        enrolledSubjectList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        enrolledSubjectList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(enrolledSubjectList);

        jList5.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane6.setViewportView(jList5);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel11.setText("~double click to check syllabus");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(178, 178, 178)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap(711, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Main ", jPanel1);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Select Subject");

        selectSubjectCbx.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        selectSubjectCbx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectSubjectCbxItemStateChanged(evt);
            }
        });
        selectSubjectCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSubjectCbxActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Required Prerequisites");

        prerequisiteList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(prerequisiteList);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Enroll");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Price:");

        selectedSubjectPriceLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectSubjectCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectedSubjectPriceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(98, 98, 98)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(938, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(selectSubjectCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(selectedSubjectPriceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Enroll Subject", jPanel2);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Pending Payments:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Completed Payments");

        completedEnrollementList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(completedEnrollementList);

        pendingPaymentList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pendingPaymentList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        pendingPaymentList.setToolTipText("");
        jScrollPane3.setViewportView(pendingPaymentList);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Select Payment Method");

        selectedPaymentMethod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        selectedPaymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VisaCard", "PayPal" }));
        selectedPaymentMethod.setSelectedItem(null);
        selectedPaymentMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedPaymentMethodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dynamicPaymentMethodPanelLayout = new javax.swing.GroupLayout(dynamicPaymentMethodPanel);
        dynamicPaymentMethodPanel.setLayout(dynamicPaymentMethodPanelLayout);
        dynamicPaymentMethodPanelLayout.setHorizontalGroup(
            dynamicPaymentMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dynamicPaymentMethodPanelLayout.setVerticalGroup(
            dynamicPaymentMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectedPaymentMethod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dynamicPaymentMethodPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(77, 77, 77)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(671, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectedPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dynamicPaymentMethodPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Payments", jPanel3);

        dynamicUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dynamicUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(679, 679, 679))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(dynamicUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectSubjectCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSubjectCbxActionPerformed
        // TODO add your handling code here:
        Subject selectedSubject = (Subject) selectSubjectCbx.getSelectedItem();
        if (selectedSubject != null) {
            DefaultListModel<Subject> prerequisites = new DefaultListModel<>();
            prerequisites.addAll(selectedSubject.getPrerequisites());
            selectedSubjectPriceLbl.setText(String.valueOf(selectedSubject.getSubjectPrice()) + " $");
            prerequisiteList.setModel(prerequisites);
        }
    }//GEN-LAST:event_selectSubjectCbxActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        JTabbedPane sourceTabbedPane = (JTabbedPane) evt.getSource();
        int selectedIndex = sourceTabbedPane.getSelectedIndex();

        if (selectedIndex == 1) { // Checking if "Settings" tab is clicked
            DefaultComboBoxModel<Subject> subjectModelCbx = new DefaultComboBoxModel<>();
            List<Subject> currentSubjects = EnrollController.getAvailableSubjects(loggedStudent);
            subjectModelCbx.addElement(null);
            for (Subject subject : currentSubjects) {
                subjectModelCbx.addElement(subject);
            }
            selectSubjectCbx.setModel(subjectModelCbx);
        }
        if (selectedIndex == 2) {
            DefaultListModel<Enroll> pendingEnrollModel = new DefaultListModel<>();
            List<Enroll> pendingEnroll = EnrollController.getDuePaymentsForStudent(loggedStudent.getId());
            pendingEnrollModel.addAll(pendingEnroll);
            pendingPaymentList.setModel(pendingEnrollModel);
            DefaultListModel<Enroll> completedEnrollementListModel = new DefaultListModel<>();
            List<Enroll> completedEnrollement = EnrollController.getFinishedPayment(loggedStudent.getId());
            completedEnrollementListModel.addAll(completedEnrollement);
            completedEnrollementList.setModel(completedEnrollementListModel);
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void selectSubjectCbxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectSubjectCbxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_selectSubjectCbxItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Subject selectedSubject = (Subject) selectSubjectCbx.getSelectedItem();
        Enroll enroll = new Enroll(enrollStatus.PendingPayment, loggedStudent, selectedSubject);
        EnrollController.addEnrollment(enroll);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void selectedPaymentMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedPaymentMethodActionPerformed
        // TODO add your handling code here:
        // Clear previous content
        dynamicPaymentMethodPanel.removeAll();
        dynamicPaymentMethodPanel.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5); // Padding

        // Handle selected payment method
        switch ((String) selectedPaymentMethod.getSelectedItem()) {
            case "VisaCard":
                // VisaCard Payment Form UI
                JLabel visaCardLabel = new JLabel("VisaCard Number");
                visaCardLabel.setFont(new Font("Arial", Font.PLAIN, 18));
                gbc.gridy = 0;
                dynamicPaymentMethodPanel.add(visaCardLabel, gbc);

                JTextField visaCardTextField = new JTextField(20);
                visaCardTextField.setFont(new Font("Arial", Font.PLAIN, 18));
                gbc.gridy = 1;
                dynamicPaymentMethodPanel.add(visaCardTextField, gbc);

                JLabel visaCardCvcLabel = new JLabel("Three-Digit Code (CVC)");
                visaCardCvcLabel.setFont(new Font("Arial", Font.PLAIN, 18));
                gbc.gridy = 2;
                dynamicPaymentMethodPanel.add(visaCardCvcLabel, gbc);

                JTextField visaCardCvcField = new JTextField(4);
                visaCardCvcField.setFont(new Font("Arial", Font.PLAIN, 18));
                gbc.gridy = 3;
                dynamicPaymentMethodPanel.add(visaCardCvcField, gbc);

                JButton visaCardButton = new JButton("Proceed with VisaCard");
                visaCardButton.setFont(new Font("Arial", Font.PLAIN, 18));
                gbc.gridy = 4;
                visaCardButton.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        String cardNumber = visaCardTextField.getText();
                        String cvc = visaCardCvcField.getText();
                        VisaCard visaCard = (VisaCard) PaymentMethodFactory.createPaymentMethod(paymentMethod.VisaCard, null, null, cardNumber, cardNumber);
                        // SELECTING ENROLL
                        Enroll selectedEnroll = pendingPaymentList.getSelectedValue();
                        // UPDATING PAYMENT
                        Payment newPayment = selectedEnroll.getPayment();
                        newPayment.setPaymentMethod(paymentMethod.VisaCard);
                        newPayment.setPaymentMethodId(visaCard.getId());
                        newPayment.setStatus(true);
                        PaymentController.updatePayment(newPayment);
                        selectedEnroll.setPayment(newPayment);
                        selectedEnroll.setStatus(enrollStatus.Active);
                        EnrollController.updateEnrollment(selectedEnroll);
                        VisaCardController.addVisaCard(visaCard);
                        visaCardTextField.setText(null);
                        visaCardCvcField.setText(null);
                    }
                });
                dynamicPaymentMethodPanel.add(visaCardButton, gbc);
                break;

            case "PayPal":
                // PayPal Payment Form UI
                JLabel payPalLabel = new JLabel("PayPal Username");
                payPalLabel.setFont(new Font("Arial", Font.PLAIN, 18));
                gbc.gridy = 0;
                dynamicPaymentMethodPanel.add(payPalLabel, gbc);

                JTextField payPalUsernameField = new JTextField(20);
                payPalUsernameField.setFont(new Font("Arial", Font.PLAIN, 18));
                gbc.gridy = 1;
                dynamicPaymentMethodPanel.add(payPalUsernameField, gbc);

                JLabel payPalPasswordLabel = new JLabel("PayPal Password");
                payPalPasswordLabel.setFont(new Font("Arial", Font.PLAIN, 18));
                gbc.gridy = 2;
                dynamicPaymentMethodPanel.add(payPalPasswordLabel, gbc);

                JPasswordField payPalPasswordField = new JPasswordField(20);
                payPalPasswordField.setFont(new Font("Arial", Font.PLAIN, 18));
                gbc.gridy = 3;
                dynamicPaymentMethodPanel.add(payPalPasswordField, gbc);

                JButton payPalButton = new JButton("Proceed with PayPal");
                payPalButton.setFont(new Font("Arial", Font.PLAIN, 18));
                gbc.gridy = 4;
                payPalButton.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        String username = payPalUsernameField.getText();
                        String password = new String(payPalPasswordField.getPassword());
                        // Handle PayPal payment logic
                        Paypal paypal = (Paypal) PaymentMethodFactory.createPaymentMethod(paymentMethod.Paypal, username, password, null, null);
                        // SELECTING ENROLL
                        Enroll selectedEnroll = pendingPaymentList.getSelectedValue();
                        // UPDATING PAYMENT
                        Payment newPayment = selectedEnroll.getPayment();
                        newPayment.setPaymentMethod(paymentMethod.Paypal);
                        newPayment.setPaymentMethodId(paypal.getId());
                        newPayment.setStatus(true);
                        PaymentController.updatePayment(newPayment);
                        selectedEnroll.setPayment(newPayment);
                        selectedEnroll.setStatus(enrollStatus.Active);
                        EnrollController.updateEnrollment(selectedEnroll);
                        PayPalController.addPaypal(paypal);
                        payPalUsernameField.setText(null);
                        payPalPasswordField.setText(null);
                    }
                });
                dynamicPaymentMethodPanel.add(payPalButton, gbc);
                break;

            default:
                // Default message if no payment method is selected
                JLabel defaultLabel = new JLabel("Please select a payment method.");
                defaultLabel.setFont(new Font("Arial", Font.PLAIN, 18));
                gbc.gridy = 0;
                dynamicPaymentMethodPanel.add(defaultLabel, gbc);
                break;
        }
        
        // Revalidate and repaint to update the panel
        dynamicPaymentMethodPanel.revalidate();
        dynamicPaymentMethodPanel.repaint();
    }//GEN-LAST:event_selectedPaymentMethodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Main().setVisible(true);
            }
        });
    }

    @Override
    public void dispose() {
        loggedStudent.setOnlineStatus(false);
        loggedStudent.setStudentMainScreen(null);
        StudentController.updateStudent(loggedStudent);
        super.dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Enroll> completedEnrollementList;
    private javax.swing.JPanel dynamicPaymentMethodPanel;
    private javax.swing.JLabel dynamicUsername;
    private javax.swing.JList<Subject> enrolledSubjectList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<Enroll> pendingPaymentList;
    private javax.swing.JList<Subject> prerequisiteList;
    private javax.swing.JComboBox<Subject> selectSubjectCbx;
    private javax.swing.JComboBox<String> selectedPaymentMethod;
    private javax.swing.JLabel selectedSubjectPriceLbl;
    // End of variables declaration//GEN-END:variables
}
